services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000

    ports:
      - "3100:3100"

    environment:
      NODE_ENV: production
      PORT: 3100

    restart: unless-stopped